# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: litecow_common/litecow.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='litecow_common/litecow.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1clitecow_common/litecow.proto\"W\n\x15\x43omputerVisionRequest\x12\x11\n\tmodel_key\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12\x14\n\x0cimages_bytes\x18\x03 \x03(\x0c\" \n\x0cResponseDict\x12\x10\n\x08response\x18\x01 \x01(\t2C\n\x04ICOW\x12;\n\x10get_cv_inference\x12\x16.ComputerVisionRequest\x1a\r.ResponseDict\"\x00\x62\x06proto3'
)




_COMPUTERVISIONREQUEST = _descriptor.Descriptor(
  name='ComputerVisionRequest',
  full_name='ComputerVisionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_key', full_name='ComputerVisionRequest.model_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_version', full_name='ComputerVisionRequest.model_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='images_bytes', full_name='ComputerVisionRequest.images_bytes', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=119,
)


_RESPONSEDICT = _descriptor.Descriptor(
  name='ResponseDict',
  full_name='ResponseDict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='ResponseDict.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['ComputerVisionRequest'] = _COMPUTERVISIONREQUEST
DESCRIPTOR.message_types_by_name['ResponseDict'] = _RESPONSEDICT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComputerVisionRequest = _reflection.GeneratedProtocolMessageType('ComputerVisionRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTERVISIONREQUEST,
  '__module__' : 'litecow_common.litecow_pb2'
  # @@protoc_insertion_point(class_scope:ComputerVisionRequest)
  })
_sym_db.RegisterMessage(ComputerVisionRequest)

ResponseDict = _reflection.GeneratedProtocolMessageType('ResponseDict', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDICT,
  '__module__' : 'litecow_common.litecow_pb2'
  # @@protoc_insertion_point(class_scope:ResponseDict)
  })
_sym_db.RegisterMessage(ResponseDict)



_ICOW = _descriptor.ServiceDescriptor(
  name='ICOW',
  full_name='ICOW',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=155,
  serialized_end=222,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_cv_inference',
    full_name='ICOW.get_cv_inference',
    index=0,
    containing_service=None,
    input_type=_COMPUTERVISIONREQUEST,
    output_type=_RESPONSEDICT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ICOW)

DESCRIPTOR.services_by_name['ICOW'] = _ICOW

# @@protoc_insertion_point(module_scope)
